from pathlib import Path
import hashlib
import json
import re
import shutil
import subprocess
import tomllib
import zipfile

root = Path(__file__).resolve().parent.parent
repo, out = root / 'outputs/TerminatorPlus-NeoForge', root / 'outputs'
build = root / 'work/ai-hardness-4.14-build.log'
full = root / 'work/ai-hardness-4.14-full.log'
warfare = root / 'work/ai-hardness-4.14-warfare-release-final.log'
checks = full.read_text(encoding='utf-8', errors='replace')
native = warfare.read_text(encoding='utf-8', errors='replace')
passes = len(re.findall(r'\[SelfTest\] PASS ', checks))
failures = re.findall(r'\[SelfTest\] FAIL ([^\r\n]+)', checks)
known = {
    'teamdive same side native takeoffs spread before a common smash with near member first',
    'teamdive same side native takeoffs spread before a common smash with far member first',
}
assert passes + len(failures) == 130, (passes, failures)
assert set(failures).issubset(known), 'Unexpected functional failure: ' + str(failures)
assert len(re.findall(r'\[SelfTest\] PASS feedback ', checks)) == 6
assert '[SelfTest] PASS equipment vanilla levels progressively enchant and level ten has a legal maximum OP kit' in checks
assert '[SelfTest] PASS equipment border infantry retreats heals and navigates with an inward margin' in checks
assert len(re.findall(r'\[SelfTest\] PASS warfare ', native)) == 46
assert len(re.findall(r'\[SelfTest\] PASS warfare feedback ', native)) == 12
assert '[SelfTest] ALL 46 CHECKS PASSED' in native
assert not re.search(r'\[SelfTest\] FAIL ', native)
assert native.count('native delay=4 projectiles=16') == 2
budget = re.search(r'Mixed budget actual projectile maximum=(\d+) total=(\d+) owners=(\d+)', native)
assert budget and int(budget[1]) <= 64 and int(budget[2]) > 240 and int(budget[3]) == 10
for log in (checks, native):
    assert '[SelfTest] ---- summary ----' in log
    assert not re.search(r'\[SelfTest\] ERROR ', log)
    assert '[SelfTest] scenario check threw' not in log and '[SelfTest] scenario setup failed' not in log
    assert 'BUILD SUCCESSFUL' in log
assert 'BUILD SUCCESSFUL' in build.read_text(encoding='utf-8', errors='replace')
assert re.search(r'^neo_version=21\.1\.1$', (repo / 'gradle.properties').read_text(), re.M)
assert re.search(r'^mod_version=4\.14\.0-BETA$', (repo / 'gradle.properties').read_text(), re.M)

jar = repo / 'build/libs/TerminatorPlus-NeoForge-1.21.1-4.14.0-BETA.jar'
with zipfile.ZipFile(jar) as archive:
    assert archive.testzip() is None
    meta = tomllib.loads(archive.read('META-INF/neoforge.mods.toml').decode('utf-8'))
    assert meta['mods'][0]['version'] == '4.14.0-BETA' and meta['mods'][0]['modId'] == 'terminatorplus'
    deps = meta['dependencies']['terminatorplus']
    assert any(d['modId'] == 'neoforge' and d['versionRange'] == '[21.1.1,)' for d in deps)
    assert any(d['modId'] == 'superbwarfare' and d['type'] == 'optional' and d['ordering'] == 'AFTER' for d in deps)
    assert any(a['file'] == 'META-INF/accesstransformer.cfg' for a in meta['accessTransformers'])
    assert archive.read('META-INF/accesstransformer.cfg')
    assert len([n for n in archive.namelist() if n.startswith('chatter/') and not n.endswith('/')]) >= 2
    assert not any(n.startswith(('com/atsuishio/', 'assets/superbwarfare/', 'data/superbwarfare/')) for n in archive.namelist())
    class_root = repo / 'build/classes/java/main'
    classes = list(class_root.rglob('*.class'))
    assert classes
    for f in classes:
        assert archive.read(f.relative_to(class_root).as_posix()) == f.read_bytes(), f
    for name in ('WarfareSupport', 'WarfareAccess', 'VehicleCrew', 'VehiclePilot', 'superbwarfare/SuperbWarfareAccess'):
        assert archive.read('net/nuggetmc/tplus/compat/' + name + '.class')
    assert archive.read('net/nuggetmc/tplus/api/agent/legacyagent/skill/MovementBounds.class')
    assert archive.read('net/nuggetmc/tplus/bot/DefaultEquipment.class')

# Only restore the autogenerated timestamp of the isolated base server.
head = subprocess.check_output(['git', 'show', 'HEAD:run-selftest/server.properties'], cwd=repo)
properties = repo / 'run-selftest/server.properties'
current_lines, head_lines = properties.read_bytes().splitlines(), head.splitlines()
assert current_lines[0] == head_lines[0] and current_lines[2:] == head_lines[2:]
properties.write_bytes(b'\r\n'.join(head_lines) + b'\r\n')

full_summary = f'{passes} PASS / {len(failures)} FAIL / 130 total'
full_zh = f'{passes} 项通过、{len(failures)} 项失败，共 130 项'
failure_text = '；'.join(failures) if failures else '本次无；历史偶发问题仍待单独修复'
shutil.copy2(jar, out / jar.name)
for source, name in ((build, 'ai-hardness-4.14.0-build.log'), (full, 'ai-hardness-4.14.0-selftest.log'),
                     (warfare, 'ai-hardness-4.14.0-warfare.log')):
    shutil.copy2(source, out / name)
digest = hashlib.sha256(jar.read_bytes()).hexdigest().upper()
validation = f'''TerminatorPlus-NeoForge 4.14.0-BETA manual playtest
Validated: 2026-10-05
Minecraft 1.21.1; Microsoft OpenJDK 21.0.7
Final build and base regression: minimum NeoForge 21.1.1
Native integration: NeoForge 21.1.249, Superb Warfare 0.8.9.1, Kotlin for Forge 5.12.0
SBW installed JAR/source commit: 5b92ebe1da5daad9cc5e8ae28e3e06f1636f5816
Build: SUCCESSFUL
Base SelfTest: {full_summary}
Current base failure names: {failures or 'none'}
Native SelfTest: ALL 46 CHECKS PASSED (original 34 plus 12 new feedback/gear checks)
Two new base checks passed: progressive vanilla OP enchantments; real border-safe infantry retreat/healing.
Mixed actual native projectile proof: max {budget[1]} per tick, {budget[2]} total, all {budget[3]} owners served over at least 120 ticks.
Both mounted budget fixtures read native delay 4 and 16 projectiles; each emitted an actual 16-projectile burst.
Historical same-side team dive synchronization remains independently pending.
Jar: {jar.name}
Jar bytes: {jar.stat().st_size}
SHA256: {digest}
Jar inspection: CRC, version, minimum NeoForge, optional SBW ordering, explicit AT, chatter resources and every compiled main class byte confirmed.
No third-party classes or assets bundled. Source base c1fcf77; changes uncommitted and unpushed.
Logs: ai-hardness-4.14.0-selftest.log, ai-hardness-4.14.0-warfare.log, ai-hardness-4.14.0-build.log

New native checks: driver-alone versus driver-and-commander actual M1A2 cannon damage; 150-block border actual low-health retreat/braking; stable real dual-empty-gun reload while distance/skills change; sequential actual AK/AA12/RPG idle preparation including native alternate ammo choice; close native MG/vehicle_strike damage; preloaded covered RPG actual tank damage and withdrawal; low-health tank does not retreat from native-zero-damage infantry; level-seven covered native 100-tick RPG reload followed by reacquisition/damage; actual-team bait/flank with native lateral RPG owner/damage; finite native 40-tick medical kit healing/regeneration; weapon-disabled native driving causes real vehicle_strike; all 1-10 SBW kits registry/armor/owned ammo/progressive enchantments/settings persistence.
Existing rifle 5v5 fixture now starts with empty AK and AA12: all ten owners fire real native projectiles, move, and preserve pearls/fireworks while in usable rifle range.
The cannon comparison also passed before the production safety change: commander obstruction is unconfirmed, intermittent non-firing is not declared fully diagnosed.

Gear defaults: /bot settings gear vanilla|warfare; explicit presets take priority. Existing bots: /bot inventory default <mode> <1-10> [bot|all], AI difficulty unchanged. SBW kit only SBW items except universal totem/elytra/firework/pearl. Native SBW armor has registered helmet/chest only, no vanilla leg/feet substitutes. Guns explicitly reject enchantments; supported armor/blades/elytra receive progressive legal enchantments. Vanilla ten receives a maximum legal OP kit. Medical kit and crust use native item completion; armor plates/grenades/smoke/C4/TM62/detonator are inventory provisions only, autonomous use pending.
Vehicle physics and movement limits remain native; no position/velocity/rotation writes. Difficulty ten supplies native energy/reserve but retains reload/heat and does not repair vehicle health.
Updated full report arrived during development: helicopter strafing/AA evasion/passenger firing angles, lost-target vehicle return, tail-side boarding and multicrew suggestions remain a later batch. Border safeguards are implemented but no new helicopter border acceptance scenario was added.
Guidance/decoy effectiveness, special weapons, fixed-wing/ship/drone driving, indirect artillery, radar and 10EX remain unvalidated or unimplemented per SUPERB_WARFARE.md.
Tests do not establish 100-bot TPS or asynchronous AI. All world/AI work remains on the server thread.
All tests ran on isolated servers. The live server was not operated or modified. Formal-server rifle 5v5, M1A2 duels, and infantry-RPG acceptance still require user playtesting.
'''
(out / 'validation-4.14.0.txt').write_text(validation, encoding='utf-8')

progress_file = repo / 'AI_HARDNESS_PROGRESS.md'
progress = progress_file.read_text(encoding='utf-8')
progress = progress.replace('更新：2026-10-05，4.13.0-BETA。', '更新：2026-10-05，4.14.0-BETA。', 1)
marker = '## 当前修正批次\n\n'
before, history = progress.split(marker, 1)
new = f'''4.14 已封装本地人工内测包，处理原 4.13 附件的世界边界、换弹、近距离载具攻击、反坦克及射程内技能问题，并实现用户选择的双套分级配装。最低 NeoForge 21.1.1 构建成功；基础完整回归 **{full_zh}**，真实 0.8.9.1 专项 **46 项全部通过**。本次基础失败：{failure_text}。历史同向团队俯冲仍独立待修，不能把偶发通过视为已修复。

新增 12 个原生场景通过：单双乘员主炮对照、150 格边界低血撤退、双空枪稳定换弹、逐枪闲时预装、6 格机枪/碾压、掩体 RPG 伤害与回缩、零伤害近战不触发坦克撤退、7 级 RPG 掩体长换弹后重新接敌、同队诱饵/实际侧翼发射、有限原生医疗包、纯驾驶真实撞击、卓越前线 1–10 全套配装。主炮对照在改动前也通过，原推测未复现；增加同车排除与诊断不等于已定位全部偶发停火原因。

原有 34 项继续通过；步枪 5v5 已收紧为双空枪开始、十名 owner 全部产生实际弹丸、实际移动且射程内不消耗进攻珍珠/烟花。混合原生弹丸预算：最多 {budget[1]} 颗/tick、累计 {budget[2]} 颗、十名 owner 均获得机会；不代表百人 TPS。

配装可选择 vanilla/warfare，显式预设优先；两套 1 无附魔、2–10 逐级增加有效附魔。原版 10 为合法满附魔 OP 套；卓越前线套只使用其装备，保留图腾/鞘翅/烟花/珍珠等通用品。枪械原生拒绝附魔，头盔/胸甲/近战/鞘翅按等级附魔；没有已注册腿/鞋故留空。医疗包/食品原生使用，战术投掷物/地雷/装甲板目前仅携带，自动使用待实现。

开发期间新增链接的完整版报告另有直升机扫射、规避、乘员射界、载具回场、尾部登车等新问题，保留下一批；未标记为通过。用户正式服的 5v5、坦克对战和 RPG 目测验收仍待完成。没有部署正式服或提交/推送 GitHub。日志见交付目录 `validation-4.14.0.txt` 和 `ai-hardness-4.14.0-*.log`。

### 4.13 历史持枪与载具批次

'''
progress = before + marker + new + history
progress = progress.replace('4.13 当前交付持枪修正与载具乘员内测包。', '4.14 当前交付换弹、边界及双配装内测包。')
progress_file.write_text(progress, encoding='utf-8')

guide = f'''# 4.14.0-BETA 换弹、边界与双配装内测

适配 Minecraft 1.21.1、Java 21、Superb Warfare 0.8.9.1-final-mc1.21.1；已在 NeoForge 21.1.249 验证原生兼容。TerminatorPlus 单独运行仍支持 21.1.1。

关服后备份旧 JAR，再替换 mods 内 TerminatorPlus，避免两版同时存在。卓越前线和原有依赖保持原安装。包内未捆绑第三方模组，本次没有操作正式服。

## 选择两套分级配装

```mcfunction
/bot preset use none
/bot settings defaultgear true
/bot settings gear warfare
/bot settings hardness 7
/bot create RifleBot
```

这些设置会保存，warfare 模式需准确版本卓越前线；自定义预设优先。切回原版用 `/bot settings gear vanilla`。等待生成后可用 `/bot inventory default warfare 7 RifleBot` 替换该机器人的装备，指令只改装备，AI 等级保持原值；末尾写 `all` 则更换所有机器人。装备及数量的 1–10 逐级表见 `SUPERB_WARFARE.md`。

原版 1 无附魔，此后逐级增加，10 为合法满附魔下界合金 OP 套，兼有剑斧、弓、重锤、鞘翅和有限图腾。卓越前线套使用原生枪、刀/合金剑、头盔/胸甲、弹药、医疗包与面包壳；保留通用图腾、鞘翅、烟花和珍珠。7+ 配 RPG；9+ 加 AWM、C4、TM-62。这个版本无注册腿/鞋，不混入原版护甲。原生枪不支持附魔，仅受支持装备逐级附魔。

8–10 会实际使用医疗包和食品。烟雾弹、手雷、装甲板、C4、TM-62 与引爆器目前只配给，自动使用待后续开发。新发枪是空膛，准备阶段请让机器人有时间依次完成真实换弹；没有直接填满弹匣。

## 本轮行为

- 换弹期间保留枪械，普通距离变化/主动拉近技能不抢手；切枪增加迟滞。无敌人时依次预装真实枪，包括 100 tick 的 RPG。
- 当前步枪已能射击时，不用珍珠或鞘翅直接冲到敌人身边。紧急撤离、脱困和抢位仍按原条件处理。
- 自主移动目标约束世界边界；坦克撤退有终点，并用原生刹车留惯性余量。低血坦克对原生零伤害近战不盲目撤退。
- 近处步兵可用原生机枪和驾驶碾压；爆炸安全距离按原生两倍半径评估，阻止朝近处障碍发射。车载射线排除同车乘员，随身枪仍检查同车友军。
- 7+ RPG 尝试真实掩体预装、侧后露头、发射后回缩；同队可以分诱饵/侧翼。长期换弹后搜索实际观察过的位置。

乘员指令沿用 `/bot vehicle crew <队长> nearest`、`board <机器人> <UUID> <座位>`、`go <驾驶员> <x> <y> <z>` 与 `leave`。`/bot vehicle status <机器人>` 和 `/bot info <机器人>` 增加装弹、瞄准、安全等待诊断。驾驶只使用原生输入。

## 建议复测

1. 5 级 AK-47+AA-12 的 5v5，两队 60 格：先按兵不动预装，再交战；检查所有人能开火、不会在双空枪间卡换弹，也不会立即冲成霰弹贴脸。
2. 150 格边界的 10 级 M1A2 双人对战，相距 70 格：观察主炮、低血撤退、停车和乘员存活；偶发不开炮时记录 `vehicle status`。
3. RPG 步兵对坦克：先装好弹，放真实可走掩体；观察侧翼开火和回缩。无遮蔽地形不保证能活着装弹。
4. 原版与卓越前线套分别检查 1、7、10 级装备、附魔、有限图腾及医疗包消耗。

## 结果和待修

真实卓越前线专项 **46/46 通过**；基础完整回归 **{full_zh}**。基础失败：{failure_text}。历史同向团队俯冲仍待单独修复。最低版本构建成功，JAR 完整性与主类逐字节检查通过；SHA256 和完整日志在包内。

单双乘员主炮对照在修改前也通过，尚未证实偶发不开炮就是车长遮挡。正式服三种对战仍需人工验收。开发期间补充的完整版报告新增直升机扫射/规避/乘员射界、载具回场、尾部登车等问题，留下一批；当前直升机只追加边界控制，不能视作这些问题已修好。

特殊制导/诱饵效果、复杂地形起降、投掷物/地雷自动操作、无人机和 10EX 仍未完成专门验收。没有百人 TPS 或异线程 AI 结论。范围和实现入口见 `SUPERB_WARFARE.md`、`AI_HARDNESS_PROGRESS.md` 与 `AGENTS.md`。
'''
(out / '4.14.0-内测说明.md').write_text(guide, encoding='utf-8')
package = out / 'TerminatorPlus-NeoForge-4.14.0-内测包.zip'
docs = ['README.md', 'AGENTS.md', 'AI_HARDNESS.md', 'AI_HARDNESS_PROGRESS.md', 'SUPERB_WARFARE.md',
        'docs/ai-hardness-handoff.md', 'docs/superbwarfare-compat-notes.md', 'docs/feedback-4.12-guns.md',
        'docs/feedback-4.13.md', 'docs/playtest-observations.md', 'docs/playtest-report-4.13.md']
contents = [(out / jar.name, jar.name), (out / '4.14.0-内测说明.md', '内测说明.md')]
contents += [(repo / n, n) for n in docs]
contents += [(out / n, n) for n in ('validation-4.14.0.txt', 'ai-hardness-4.14.0-build.log',
                                  'ai-hardness-4.14.0-selftest.log', 'ai-hardness-4.14.0-warfare.log')]
with zipfile.ZipFile(package, 'w', zipfile.ZIP_DEFLATED) as archive:
    for source, name in contents:
        archive.write(source, name)
with zipfile.ZipFile(package) as archive:
    assert archive.testzip() is None and archive.read(jar.name) == jar.read_bytes()
assert (out / jar.name).read_bytes() == jar.read_bytes()
print(json.dumps({'jar': jar.name, 'jar_bytes': jar.stat().st_size, 'sha256': digest,
                  'package_bytes': package.stat().st_size, 'zip_sha256': hashlib.sha256(package.read_bytes()).hexdigest().upper(),
                  'base': full_summary, 'native': 'ALL 46 CHECKS PASSED', 'classes_verified': len(classes)}, ensure_ascii=True))
